trigger:
- master
pr:
- develop
- master

strategy:
  matrix:
    windows-stable:
      imageName: 'windows-2019'
      rustup_toolchain: nightly
    mac-stable:
      imageName: 'macos-10.14'
      rustup_toolchain: nightly
    linux-stable:
      imageName: 'ubuntu-18.04'
      rustup_toolchain: nightly

pool:
  vmImage: $(imageName)

steps:
  - script: cd packages/catalyst-common && cargo build --all --verbose
    displayName: Cargo build
  - script: cd packages/catalyst-common && cargo test --all --verbose
    displayName: Cargo test
  - script: cd packages/catalyst-common && cargo test --features key-gen
    displayName: Cargo test key-gen build